import { describe, it, expect } from 'vitest';
import { truncateData } from './cloud-tasks-util';

it('truncates too large data max 1 KB', () => {
  const truncated = truncateData(mockData as any, 'test-queue', 1);
  expect(truncated).not.toEqual({});
  const bytes = Buffer.byteLength(JSON.stringify(truncated), 'utf8');
  expect(bytes).toBeLessThanOrEqual(1 * 1024);
});

it('doesnt truncate when not exceeding limit', () => {
  const truncated = truncateData(mockData as any, 'test-queue', 20);
  expect(truncated).toEqual(mockData);
});

// Mock data is 7 kb, should be truncated
const mockData = {
  ctx: {
    _req: {
      _readableState: {
        state: 325654,
        highWaterMark: 16384,
        length: 0,
        pipes: [],
        flowing: true,
        errored: null,
        defaultEncoding: 'utf8',
        awaitDrainWriters: null,
        decoder: null,
        encoding: null,
      },
      _events: {},
      _eventsCount: 0,
      socket: {
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: null,
        _closeAfterHandlingError: false,
        _eventsCount: 8,
        allowHalfOpen: true,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        parser: null,
        _paused: false,
        _httpMessage: null,
        timeout: 5000,
        bytesRead: 1167,
        _bytesDispatched: 489,
        bytesWritten: 489,
      },
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [
        'host',
        'wkw-prod-api.pinelab.app',
        'content-length',
        '125',
        'sec-ch-ua-platform',
        '"Windows"',
        'authorization',
        'Bearer 8086c922cda62d3591e71f492fedbe72ddc1704fe1bb8fd0cdf484cca0a925f2',
        'vendure-token',
        'wkw-retail',
        'user-agent',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36 Edg/138.0.0.0',
        'sec-ch-ua',
        '"Not)A;Brand";v="8", "Chromium";v="138", "Microsoft Edge";v="138"',
        'content-type',
        'application/json',
        'sec-ch-ua-mobile',
        '?0',
        'accept',
        '*/*',
        'origin',
        'https://wormenkwekerijwasse.nl',
        'sec-fetch-site',
        'cross-site',
        'sec-fetch-mode',
        'cors',
        'sec-fetch-dest',
        'empty',
        'referer',
        'https://wormenkwekerijwasse.nl/',
        'accept-language',
        'nl,en;q=0.9,en-GB;q=0.8,en-US;q=0.7',
        'priority',
        'u=1, i',
        'x-cloud-trace-context',
        'a7fe3c442ba112ae4655c6118a6f499e/4504047268901045129',
        'x-forwarded-proto',
        'https',
        'traceparent',
        '00-a7fe3c442ba112ae4655c6118a6f499e-3e819720aa6a4389-00',
        'x-forwarded-for',
        '161.51.81.13',
        'forwarded',
        'for="161.51.81.13";proto=https',
        'accept-encoding',
        'gzip, deflate, br, zstd',
      ],
      rawTrailers: [],
      joinDuplicateHeaders: null,
      aborted: false,
      upgrade: false,
      url: '/?languageCode=nl',
      method: 'POST',
      statusCode: null,
      statusMessage: null,
      client: {
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: null,
        _closeAfterHandlingError: false,
        _eventsCount: 8,
        allowHalfOpen: true,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        parser: null,
        _paused: false,
        _httpMessage: null,
        timeout: 5000,
        bytesRead: 1167,
        _bytesDispatched: 489,
        bytesWritten: 489,
      },
      _consuming: true,
      _dumped: false,
      next: {},
      baseUrl: '/shop-api',
      originalUrl: '/shop-api?languageCode=nl',
      _parsedUrl: {
        protocol: null,
        slashes: null,
        auth: null,
        host: null,
        port: null,
        hostname: null,
        hash: null,
        search: '?languageCode=nl',
        query: 'languageCode=nl',
        pathname: '/shop-api',
        path: '/shop-api?languageCode=nl',
        href: '/shop-api?languageCode=nl',
        _raw: '/shop-api?languageCode=nl',
      },
      params: {},
      query: { languageCode: 'nl' },
      res: {
        _eventsCount: 1,
        outputData: [],
        outputSize: 0,
        writable: true,
        destroyed: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        maxRequestsOnConnectionReached: false,
        _defaultKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        strictContentLength: false,
        _contentLength: '41',
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        _closed: true,
        socket: null,
        _header:
          'HTTP/1.1 200 OK\r\nX-Powered-By: Express\r\nAccess-Control-Allow-Origin: https://wormenkwekerijwasse.nl\r\nVary: Origin\r\nAccess-Control-Allow-Credentials: true\r\nAccess-Control-Expose-Headers: vendure-auth-token\r\nContent-Language: nl\r\ncache-control: no-store\r\nContent-Type: application/json; charset=utf-8\r\nContent-Length: 41\r\nETag: W/"29-SRIkDE7OG1QqOFzAY8i60y5NzBs"\r\nDate: Thu, 07 Aug 2025 10:43:10 GMT\r\nConnection: keep-alive\r\nKeep-Alive: timeout=5\r\n\r\n',
        _keepAliveTimeout: 5000,
        _sent100: false,
        _expect_continue: false,
        _maxRequestsPerSocket: 0,
        statusCode: 200,
        statusMessage: 'OK',
        headersSent: true,
      },
      body: {
        query:
          '\n  mutation klaviyoCheckoutStarted {\n    klaviyoCheckoutStarted\n  }\n',
        operationName: 'klaviyoCheckoutStarted',
      },
      _body: true,
      rawBody: {
        '0': 123,
        '1': 34,
        '2': 113,
        '3': 117,
        '4': 101,
        '5': 114,
        '6': 121,
        '7': 34,
        '8': 58,
        '9': 34,
        '10': 92,
        '11': 110,
        '12': 32,
        '13': 32,
        '14': 109,
        '15': 117,
        '16': 116,
        '17': 97,
        '18': 116,
        '19': 105,
        '20': 111,
        '21': 110,
        '22': 32,
        '23': 107,
        '24': 108,
        '25': 97,
        '26': 118,
        '27': 105,
        '28': 121,
        '29': 111,
        '30': 67,
        '31': 104,
        '32': 101,
        '33': 99,
        '34': 107,
        '35': 111,
        '36': 117,
        '37': 116,
        '38': 83,
        '39': 116,
        '40': 97,
        '41': 114,
        '42': 116,
        '43': 101,
        '44': 100,
        '45': 32,
        '46': 123,
        '47': 92,
        '48': 110,
        '49': 32,
        '50': 32,
        '51': 32,
        '52': 32,
        '53': 107,
        '54': 108,
        '55': 97,
        '56': 118,
        '57': 105,
        '58': 121,
        '59': 111,
        '60': 67,
        '61': 104,
        '62': 101,
        '63': 99,
        '64': 107,
        '65': 111,
        '66': 117,
        '67': 116,
        '68': 83,
        '69': 116,
        '70': 97,
        '71': 114,
        '72': 116,
        '73': 101,
        '74': 100,
        '75': 92,
        '76': 110,
        '77': 32,
        '78': 32,
        '79': 125,
        '80': 92,
        '81': 110,
        '82': 34,
        '83': 44,
        '84': 34,
        '85': 111,
        '86': 112,
        '87': 101,
        '88': 114,
        '89': 97,
        '90': 116,
        '91': 105,
        '92': 111,
        '93': 110,
        '94': 78,
        '95': 97,
        '96': 109,
        '97': 101,
        '98': 34,
        '99': 58,
        '100': 34,
        '101': 107,
        '102': 108,
        '103': 97,
        '104': 118,
        '105': 105,
        '106': 121,
        '107': 111,
        '108': 67,
        '109': 104,
        '110': 101,
        '111': 99,
        '112': 107,
        '113': 111,
        '114': 117,
        '115': 116,
        '116': 83,
        '117': 116,
        '118': 97,
        '119': 114,
        '120': 116,
        '121': 101,
        '122': 100,
        '123': 34,
        '124': 125,
        offset: 1080,
      },
      i18nextLookupName: 'querystring',
      lng: 'nl',
      locale: 'nl',
      language: 'nl',
      languages: ['nl', 'en'],
      i18n: {
        language: 'nl',
        isInitializing: false,
        languages: ['nl', 'en'],
        resolvedLanguage: 'en',
        isInitialized: true,
      },
      t: {},
      vendureRequestContextMap: {},
      vendureRequestContext: {},
      app: { _eventsCount: 1, mountpath: '/' },
      header: {},
      get: {},
      accepts: {},
      acceptsEncodings: {},
      acceptsEncoding: {},
      acceptsCharsets: {},
      acceptsCharset: {},
      acceptsLanguages: {},
      acceptsLanguage: {},
      range: {},
      param: {},
      is: {},
      protocol: 'http',
      secure: false,
      ips: [],
      subdomains: ['wkw-prod-api'],
      path: '/',
      hostname: 'wkw-prod-api.pinelab.app',
      fresh: false,
      stale: true,
      xhr: false,
      setTimeout: {},
      _read: {},
      _destroy: {},
      _addHeaderLines: {},
      _addHeaderLine: {},
      _addHeaderLineDistinct: {},
      _dump: {},
      destroy: {},
      _undestroy: {},
      push: {},
      unshift: {},
      isPaused: {},
      setEncoding: {},
      read: {},
      pipe: {},
      unpipe: {},
      on: {},
      addListener: {},
      removeListener: {},
      off: {},
      removeAllListeners: {},
      resume: {},
      pause: {},
      wrap: {},
      iterator: {},
      setMaxListeners: {},
      getMaxListeners: {},
      emit: {},
      prependListener: {},
      once: {},
      prependOnceListener: {},
      listeners: {},
      rawListeners: {},
      listenerCount: {},
      eventNames: {},
    },
    _apiType: 'shop',
    _channel: {
      token: 'wkw-retail',
      createdAt: '2025-02-13T14:32:48.512Z',
      updatedAt: '2025-07-18T12:34:54.336Z',
      code: 'WKW retail',
      description: '',
      defaultLanguageCode: 'nl',
      availableLanguageCodes: ['nl'],
      defaultCurrencyCode: 'EUR',
      availableCurrencyCodes: ['EUR'],
      trackInventory: true,
      outOfStockThreshold: 0,
      pricesIncludeTax: true,
      id: 3,
      sellerId: 1,
      customFields: {
        orderConfirmationRecipient: null,
        emailSender: 'info@wormenkwekerijwasse.nl',
        storefrontUrl: 'https://wormenkwekerijwasse.nl',
        allowReverseTaxCharge: 1,
        ggEnabled: null,
        ggUuidApiKey: null,
      },
      defaultShippingZone: {
        createdAt: '2021-08-18T12:26:26.986Z',
        updatedAt: '2021-10-29T12:29:00.000Z',
        name: 'NL',
        id: 6,
      },
      defaultTaxZone: {
        createdAt: '2021-08-18T12:26:26.986Z',
        updatedAt: '2021-10-29T12:29:00.000Z',
        name: 'NL',
        id: 6,
      },
    },
    _session: {
      cacheExpiry: 1754563566.642,
      id: 677550,
      token: '8086c922cda62d3591e71f492fedbe72ddc1704fe1bb8fd0cdf484cca0a925f2',
      expires: '2026-08-07T12:58:00.000Z',
      activeOrderId: 66571,
      activeChannelId: 3,
    },
    _languageCode: 'nl',
    _currencyCode: 'EUR',
    _isAuthorized: false,
    _authorizedAsOwnerOnly: false,
  },
  event: {
    eventName: 'Checkout Started',
    uniqueId: '7545-6326-65-FEQ_2025-08-07',
    customProperties: {
      orderCode: '7545-6326-65-FEQ',
      orderItems: [
        {
          productName: 'Wormery wormenbak 4 lagen met compostwormen',
          quantity: 1,
        },
      ],
    },
    profile: {
      emailAddress: 'frankbudde1975@gmail.com',
      externalId: '24608',
      firstName: 'Frank',
      lastName: 'Budde',
      phoneNumber: '',
      address: {
        address1: 'HemsinkHemsink',
        address2: '26',
        city: 'Biddinghuizen',
        postalCode: '8256JJ',
        countryCode: 'nl',
      },
    },
  },
};
